fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                word:
                    mappings:
                        meanings:
                            type: "nested"
                            properties:
                                meaning: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Word